apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitbucket
  template:
    metadata:
      name: gitbucket
      labels:
        app: gitbucket
    spec: 
      containers:
        - name: gitbucket
          image: gitbucket/gitbucket:latest
          ports:
            - containerPort: 8080
