apiVersion: apps/v1
kind: Deployment
metadata:
  name: myngpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myngpod
  template:
    metadata:
      name: myngpod
      labels:
        app: myngpod
    spec: 
      containers:
        - name: myngpod
          image: nginx:latest
          ports:
            - containerPort: 80
