apiVersion: apps/v1
kind: Pod
metadata:
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      name: myweb
      labels:
        app: myweb
    spec: 
      containers:
        - name: myweb
          image: nginx:latest
          ports:
            - containerPort: 80
